/* Gravital Talk C ABI. Auto-generated by cbindgen. Do not edit. */

#ifndef GRAVITAL_TALK_H
#define GRAVITAL_TALK_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Versión ABI estable.
 */
#define GS_ABI_VERSION 1

/*
 Estado dinámico de una sesión para consumidores C.
 */
enum GsSessionState
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    GS_STATE_IDLE = 0,
    GS_STATE_HANDSHAKING = 1,
    GS_STATE_ACTIVE = 2,
    GS_STATE_PAUSED = 3,
    GS_STATE_CLOSING = 4,
    GS_STATE_CLOSED = 5,
    GS_STATE_ERROR = 6,
    GS_STATE_RECONNECTING = 7,
};
#ifndef __cplusplus
typedef uint8_t GsSessionState;
#endif // __cplusplus

/*
 Códigos de error. `GS_OK = 0`.
 */
typedef enum {
    GS_OK = 0,
    GS_ERR_NULL_POINTER = -1,
    GS_ERR_INVALID_ARGUMENT = -2,
    GS_ERR_IO = -3,
    GS_ERR_TIMEOUT = -4,
    GS_ERR_HANDSHAKE = -5,
    GS_ERR_PROTOCOL = -6,
    GS_ERR_INVALID_STATE = -7,
    GS_ERR_CLOSED = -8,
    GS_ERR_BUFFER_TOO_SMALL = -9,
    GS_ERR_INTERNAL = -99,
} GsStatus;

/*
 Configuración pasada desde C a `gs_session_create`.
 */
typedef struct {
    uint32_t sample_rate;
    uint8_t channels;
    uint8_t frame_duration_ms;
    uint32_t max_bitrate;
    uint8_t codec_preferred;
    uint32_t capability_flags;
    uint16_t jitter_buffer_ms;
    uint32_t mtu;
} GsConfig;

/*
 Handle opaco a una sesión.
 */
typedef struct {
    uint8_t _private[0];
} GsSessionHandle;

/*
 Layout binario idéntico a `MetricsSnapshot`. Ver `docs/protocol-spec.md`.
 */
typedef struct {
    float rtt_ms;
    float jitter_ms;
    float loss_percent;
    float reorder_percent;
    float buffer_fill_percent;
    float estimated_mos;
    uint64_t packets_sent;
    uint64_t packets_received;
    uint64_t bytes_sent;
    uint64_t bytes_received;
} GsMetrics;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Devuelve la versión SemVer del crate como C-string estática.
 */
const char *gs_version(void);

/*
 Versión del protocolo wire.
 */
uint32_t gs_protocol_version(void);

/*
 Versión del ABI C.
 */
uint32_t gs_abi_version(void);

/*
 Rellena `out` con la configuración por default.

 # Safety
 `out` debe ser un puntero válido a un `GsConfig` escribible.
 */
GsStatus gs_config_default(GsConfig *out);

/*
 Crea una sesión bindeando un socket UDP.

 `bind_addr` e `bind_port` controlan el socket local; pasa `0.0.0.0:0` para
 ephemeral.

 # Safety
 `config`, `bind_addr` y `out_handle` deben ser punteros válidos. `bind_addr`
 debe apuntar a una C-string NUL-terminada.
 */
GsStatus gs_session_create(const GsConfig *config,
                           const char *bind_addr,
                           uint16_t bind_port,
                           GsSessionHandle **out_handle);

/*
 Destruye una sesión y libera su runtime. El handle pasa a ser inválido.

 # Safety
 `handle` debe haber sido creado por `gs_session_create` y no haber sido
 destruido ya. `NULL` es un no-op seguro.
 */
void gs_session_destroy(GsSessionHandle *handle);

/*
 Ejecuta el handshake como cliente hacia `peer_addr:peer_port`.
 */
GsStatus gs_session_connect(GsSessionHandle *handle, const char *peer_addr, uint16_t peer_port);

/*
 Ejecuta el handshake como servidor esperando a `peer_addr:peer_port`.
 */
GsStatus gs_session_accept(GsSessionHandle *handle, const char *peer_addr, uint16_t peer_port);

/*
 Envía un frame de audio. Requiere estado `Active`.
 */
GsStatus gs_session_send_audio(GsSessionHandle *handle, const uint8_t *data, uintptr_t len);

/*
 Recibe el próximo frame de audio. `buf` debe tener al menos `*len_inout`
 bytes; al retorno `*len_inout` contiene los bytes escritos.
 */
GsStatus gs_session_recv_audio(GsSessionHandle *handle, uint8_t *buf, uintptr_t *len_inout);

/*
 Cierra la sesión enviando `CLOSE`. El handle queda en estado `Closed`.
 */
GsStatus gs_session_close(GsSessionHandle *handle);

/*
 Devuelve el estado actual por el puntero `out_state`.
 */
GsStatus gs_session_state(GsSessionHandle *handle, GsSessionState *out_state);

/*
 Devuelve el `session_id` negociado.
 */
GsStatus gs_session_id(GsSessionHandle *handle, uint32_t *out_id);

/*
 Rellena `out` con un snapshot atómico de métricas.
 */
GsStatus gs_session_metrics(GsSessionHandle *handle, GsMetrics *out);

/*
 Devuelve el último error como C-string NUL-terminada, o NULL si no hay.
 El puntero es válido hasta la próxima llamada FFI en el mismo hilo.
 */
const char *gs_error_last(void);

/*
 Limpia el buffer de último error.
 */
void gs_error_clear(void);

/*
 Solicita el floor (permiso para transmitir).

 Envía `FloorRequest` al peer/relay. El resultado real (Grant/Deny)
 llega asíncronamente vía `dispatch_packet`.
 */
GsStatus gs_session_ptt_press(GsSessionHandle *handle);

/*
 Libera el floor (fin de transmisión).
 */
GsStatus gs_session_ptt_release(GsSessionHandle *handle);

/*
 Devuelve `1` si el peer remoto está transmitiendo actualmente, `0` si no.
 */
int gs_session_is_peer_ptt_active(GsSessionHandle *handle);

/*
 Devuelve el `local_ssrc` de la sesión.
 */
GsStatus gs_session_local_ssrc(GsSessionHandle *handle, uint32_t *out_ssrc);

/*
 Devuelve el puerto UDP local del socket de la sesión.

 Útil para incluirlo en el QR de pairing (el host lo usa como `lan_port`).

 # Safety
 `handle` debe ser válido y `out_port` no nulo.
 */
GsStatus gs_session_local_port(GsSessionHandle *handle, uint16_t *out_port);

/*
 Descubre la dirección IP pública usando STUN (stun.l.google.com:19302).

 Escribe `"ip:port"` como C-string NUL-terminada en `out_buf`.
 `buf_len` debe ser al menos 48 bytes para acomodar IPv4+puerto.

 # Safety
 `out_buf` debe apuntar a un buffer de al menos `buf_len` bytes escribibles.
 */
GsStatus gs_discover_public_addr(uint16_t local_port, char *out_buf, uintptr_t buf_len);

/*
 Handshake servidor que acepta el primer cliente que llegue desde cualquier
 dirección (modo QR/code pairing — no se requiere conocer la IP del cliente).

 Bloqueante hasta completar el handshake o agotar el timeout configurado.

 # Safety
 `handle` debe ser válido y creado con `gs_session_create`.
 */
GsStatus gs_session_accept_any(GsSessionHandle *handle);

/*
 Retorna `GS_OK` — útil como smoke test de linkado.
 */
int gs_ping(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GRAVITAL_TALK_H */
